apiVersion: v1
kind: Service
metadata:
  name: retex-api
  labels:
    app: retex-api
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: retex-api